[package]
name = "quadrant-napi"
version.workspace = true
edition = "2024"
build = "build.rs"

[features]
default = ["proprietary"]
curseforge = ["quadrant-host/curseforge"]
telemetry = []
quadrant_id = []
proprietary = ["curseforge", "telemetry", "quadrant_id"]

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { workspace = true }
napi-derive = { workspace = true }
quadrant-host = { path = "../quadrant-host" }
serde_json = { workspace = true }
tokio = { workspace = true }

[build-dependencies]
napi-build = { workspace = true }
