[package]
name = "quadrant-host"
version.workspace = true
edition = "2024"

[features]
default = []
curseforge = ["quadrant-core/curseforge"]

[dependencies]
anyhow = { workspace = true }
colog = { workspace = true }
futures = { workspace = true }
keyring = { workspace = true }
log = { workspace = true }
quadrant-core = { path = "../quadrant-core" }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tokio-tungstenite = { workspace = true }
url = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
