# @format

name: "Build for Windows/Linux"

on:
  push:
    tags:
      - "v*-stable"
      - "v*-flatpak"

# This workflow will trigger on each push to the `release` branch to create or update a GitHub release, build your app, and upload the artifacts to the release.

jobs:
  build-for-flatpak:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "ubuntu-24.04"
            args: ""

    runs-on: ${{ matrix.platform }}
    outputs:
      assets: ${{steps.tauri.outputs.releaseUploadUrl}}
      version: ${{steps.tauri.outputs.appVersion}}
    steps:
      - uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v2


      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-24.04' || matrix.platform == 'ubuntu-24.04-arm'
        run: |
          sudo apt update
          sudo apt install -y libwebkit2gtk-4.1-dev xdg-utils libappindicator3-dev librsvg2-dev patchelf libsecret-1-dev

      - name: install frontend dependencies (bun)
        run: bun install

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"

      - uses: tauri-apps/tauri-action@v0
        id: tauri
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
          ETERNAL_API_TOKEN: ${{ secrets.ETERNAL_API_TOKEN }}
          QUADRANT_API_KEY: ${{ secrets.QUADRANT_API_KEY }}
          QUADRANT_OAUTH2_CLIENT_ID: ${{ secrets.QUADRANT_OAUTH2_CLIENT_ID }}
          QUADRANT_OAUTH2_CLIENT_SECRET: ${{ secrets.QUADRANT_OAUTH2_CLIENT_SECRET }}
          NO_STRIP: ${{ (matrix.platform == 'ubuntu-24.04' || matrix.platform == 'ubuntu-24.04-arm') && 'true' }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

        with:
          releaseName: "Quadrant v__VERSION__"
          releaseBody: "See the assets to download this version and install. Check out the [changelog on my blog](https://blog.mrquantumoff.dev)"
          releaseDraft: false
          prerelease: ${{ !endsWith(github.ref_name, 'stable') }}
          args: ${{ matrix.args }} -c ./src-tauri/tauri.flatpak.conf.json
          tauriScript: 'bun tauri'
          tagName: ${{github.ref_name}}
